{
 "title": "BambuLab",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Instant Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"BambuLabs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Percentage Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mc_percent_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nozzle Temperature (C)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nozzle_temper_metric", "legendFormat": "Nozzle Temperature" },
    { "expr": "nozzle_target_temper_metric", "legendFormat": "Nozzle Target Temperature" }
   ]
  },
  {
   "title": "WiFi SIgnal in dBm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wifi_signal_metric ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMS, Bed, & Chamber Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ams_temp_metric", "legendFormat": "AMS" },
    { "expr": "chamber_temper_metric", "legendFormat": "Chamber" },
    { "expr": "ams_bed_temp_metric", "legendFormat": "Bed Temp" }
   ]
  },
  { "title": "Trending Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "up{job=\"BambuLabs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Time on Print (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "targets": [
    { "expr": "mc_remaining_time_metric", "legendFormat": "Print Job Timer" }
   ]
  },
  {
   "title": "AMS, Bed, & Chamber Temp (C)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 6 },
   "targets": [
    { "expr": "ams_temp_metric", "legendFormat": "AMS Temperature" },
    { "expr": "chamber_temper_metric", "legendFormat": "Chamber Temperature" },
    { "expr": "ams_bed_temp_metric", "legendFormat": "AMS Bed Temperature" }
   ]
  },
  {
   "title": "WiFi SIgnal in dBm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 6 },
   "targets": [
    { "expr": "wifi_signal_metric ", "legendFormat": "WiFi Signal" }
   ]
  },
  {
   "title": "Print Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "expr": "print_error_metric ", "legendFormat": "Print Error" },
    { "expr": "fail_reason_metric", "legendFormat": "Failure Reason" },
    { "expr": "mc_print_error_code_metric", "legendFormat": "Print Error Code" }
   ]
  },
  {
   "title": "Nozzle Temperature (C) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "targets": [
    { "expr": "nozzle_temper_metric", "legendFormat": "Nozzle Temperature" },
    { "expr": "nozzle_target_temper_metric", "legendFormat": "Nozzle Target Temperature" }
   ]
  },
  {
   "title": "Fan Gear Metric",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 12 },
   "targets": [
    { "expr": "fan_gear_metric", "legendFormat": "Fan Gear" }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 12 },
   "targets": [
    { "expr": "big_fan1_speed_metric ", "legendFormat": "Big Fan 1" },
    { "expr": "cooling_fan_speed_metric ", "legendFormat": "Cooling Fan" },
    { "expr": "big_fan2_speed_metric ", "legendFormat": "Big Fan 2" }
   ]
  },
  {
   "title": "MC Print Stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    { "expr": "mc_print_sub_stage_metric", "legendFormat": "Print Sub Stage" },
    { "expr": "mc_print_stage_metric", "legendFormat": "Print Stage" }
   ]
  }
 ]
}